from its.ga.types import GeneDefinition
from its.strategies.core.optimization import (
    CVaR,
    CVaRHighRisk,
    CVaRRiskParityAllocator,
    EqualRiskContributionAllocator,
    EqualWeighted,
    HierarchicalEqualRiskContributionAllocator,
    HierarchicalRiskParity,
    InverseVolatility,
    MaximumDiversificationAllocator,
    MaximumReturnAllocator,
    MaximumSharpeAllocator,
    MeanCVaRAllocator,
    MinimumCVaRAllocator,
    MinimumVarianceAllocator,
    NestedClustersOptimizationAllocator,
)

GENES = [
    GeneDefinition(
        id="equal_weighted",
        title="Equal Weighted",
        description="Allocate the selected universe with equal weights.",
        group="allocation",
        component=EqualWeighted,
    ),
    GeneDefinition(
        id="inverse_volatility",
        title="Inverse Volatility",
        description="Allocate more weight to lower-volatility assets.",
        group="allocation",
        component=InverseVolatility,
        component_kwargs={"raise_on_failure": False},
    ),
    GeneDefinition(
        id="HierarchicalRiskParity",
        title="HRP",
        description="Allocate weight hierarchical risk parity",
        group="allocation",
        component=HierarchicalRiskParity,
        component_kwargs={"raise_on_failure": False},
    ),
    GeneDefinition(
        id="CVaR",
        title="CVaR",
        description="Allocate weight CVaR",
        group="allocation",
        component=CVaR,
        component_kwargs={"beta": 0.95},
    ),
    GeneDefinition(
        id="CVaRHighRisk",
        title="CVaRHighRisk",
        description="Allocate weight CVaRHighRisk",
        group="allocation",
        component=CVaRHighRisk,
        component_kwargs={"beta": 0.95},
    ),
    GeneDefinition(
        id="minimum_variance",
        title="Minimum Variance",
        description="Minimize the portfolio variance over the selected assets.",
        group="allocation",
        component=MinimumVarianceAllocator,
        component_kwargs={"raise_on_failure": False},
    ),
    GeneDefinition(
        id="maximum_sharpe",
        title="Maximum Sharpe",
        description="Maximize the expected-return/volatility ratio of the portfolio.",
        group="allocation",
        component=MaximumSharpeAllocator,
        component_kwargs={"raise_on_failure": False},
    ),
    GeneDefinition(
        id="maximum_return",
        title="Maximum Return",
        description="Maximize the expected return of the portfolio under its bounds.",
        group="allocation",
        component=MaximumReturnAllocator,
        component_kwargs={"raise_on_failure": False},
    ),
    GeneDefinition(
        id="equal_risk_contribution",
        title="Equal Risk Contribution",
        description="Weight assets so each contributes equally to portfolio risk.",
        group="allocation",
        component=EqualRiskContributionAllocator,
        component_kwargs={"raise_on_failure": False},
    ),
    GeneDefinition(
        id="minimum_cvar",
        title="Minimum CVaR",
        description="Minimize the portfolio Conditional Value-at-Risk.",
        group="allocation",
        component=MinimumCVaRAllocator,
        component_kwargs={"raise_on_failure": False},
    ),
    GeneDefinition(
        id="mean_cvar",
        title="Mean CVaR",
        description="Balance expected return against portfolio Conditional Value-at-Risk.",
        group="allocation",
        component=MeanCVaRAllocator,
        component_kwargs={"raise_on_failure": False},
    ),
    GeneDefinition(
        id="cvar_risk_parity",
        title="CVaR Risk Parity",
        description="Weight assets so each contributes equally to CVaR tail risk.",
        group="allocation",
        component=CVaRRiskParityAllocator,
        component_kwargs={"raise_on_failure": False},
    ),
    GeneDefinition(
        id="maximum_diversification",
        title="Maximum Diversification",
        description="Maximize the portfolio diversification ratio.",
        group="allocation",
        component=MaximumDiversificationAllocator,
        component_kwargs={"raise_on_failure": False},
    ),
    GeneDefinition(
        id="hierarchical_equal_risk_contribution",
        title="HERC",
        description="Hierarchical clustering followed by equal risk contribution.",
        group="allocation",
        component=HierarchicalEqualRiskContributionAllocator,
        component_kwargs={"raise_on_failure": False},
    ),
    GeneDefinition(
        id="nested_clusters_optimization",
        title="NCO",
        description="Cluster assets, then optimize within and between clusters.",
        group="allocation",
        component=NestedClustersOptimizationAllocator,
        component_kwargs={"raise_on_failure": False},
    ),
]
